[tool.poetry]
name = "spider-utils"
version = "0.1.0"
description = ""
authors = ["Pony.Ma <pony.ma@rccchina.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
